apiVersion: v1
kind: Secret
metadata:
  name: open-webui-admin
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  email: {{ .Values.webui.admin.email | quote }}
  password: {{ .Values.webui.admin.password | quote }}
